=== angelmorexp/IFCD0210/MF0491_3 CLIENTE/UF1841/E2/xsd/Liga_Pokemon.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="ligapokemon">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="logo" type="xs:string"/>
        <xs:element ref="navegacion"/>
        <xs:element ref="altomando"/>
        <xs:element ref="campeon"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="navegacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="enlace" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="altomando">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element ref="entrenador" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="entrenador">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="especialidad" type="xs:string"/>
        <xs:element ref="equipo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="equipo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element ref="pokemon" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pokemon">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="nivel" type="xs:string"/>
        <xs:element name="tipo" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="campeon">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element ref="entrenador"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== angelmorexp/IFCD0210/MF0491_3 CLIENTE/UF1841/E2/xml/Liga_Pokemon.xml
<?xml version="1.0" encoding="UTF-8"?>


<ligapokemon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/UF1841%20M1U1/Actividades/E2/xsd/Liga_Pokemon.xsd">
  <logo>LIGA POKEMON</logo>
  <navegacion>
    <enlace>Inicio</enlace>
    <enlace>Pokemon Wiki</enlace>
    <enlace>Pokemon Oficial</enlace>
  </navegacion>
  <altomando>
  <titulo>ALTO MANDO</titulo>
    <entrenador>
      <nombre>Lorelei</nombre>
      <especialidad>Hielo</especialidad>
      <equipo>
      <titulo>EQUIPO</titulo>
      <pokemon>
      <nombre>Dewgong</nombre>
      <nivel>54</nivel>
      <tipo>Agua</tipo>
      <tipo>Hielo</tipo>
      </pokemon>
      <pokemon>
      <nombre>Cloyster</nombre>
      <nivel>53</nivel>
      <tipo>Agua</tipo>
      <tipo>Hielo</tipo>
      </pokemon>
      <pokemon>
      <nombre>Slowbro</nombre>
      <nivel>54</nivel>
      <tipo>Agua</tipo>
      <tipo>Psiquico</tipo>
      </pokemon>
      <pokemon>
      <nombre>Jynx</nombre>
      <nivel>56</nivel>
      <tipo>Hielo</tipo>
      <tipo>Psiquico</tipo>
      </pokemon>
      <pokemon>
      <nombre>Lapras</nombre>
      <nivel>56</nivel>
      <tipo>Agua</tipo>
      <tipo>Hielo</tipo>
      </pokemon>
      </equipo>
    </entrenador>
    <entrenador>
      <nombre>Bruno</nombre>
      <especialidad>Lucha</especialidad>
      <equipo>
      <titulo>EQUIPO</titulo>
      <pokemon>
      <nombre>Onix</nombre>
      <nivel>53</nivel>
      <tipo>Roca</tipo>
      <tipo>Tierra</tipo>
      </pokemon>
      <pokemon>
      <nombre>Hitmonchan</nombre>
      <nivel>55</nivel>
      <tipo>Lucha</tipo>
      </pokemon>
      <pokemon>
      <nombre>Hitmonlee</nombre>
      <nivel>55</nivel>
      <tipo>Lucha</tipo>
      </pokemon>
      <pokemon>
      <nombre>Onix</nombre>
      <nivel>56</nivel>
      <tipo>Roca</tipo>
      <tipo>Tierra</tipo>
      </pokemon>
      <pokemon>
      <nombre>Machamp</nombre>
      <nivel>58</nivel>
      <tipo>Lucha</tipo>
      </pokemon>
     
      </equipo>
    </entrenador>
    <entrenador>
      <nombre>Agatha</nombre>
      <especialidad>Fantasma</especialidad>
      <equipo>
      <titulo>EQUIPO</titulo>
      <pokemon>
      <nombre>Gengar</nombre>
      <nivel>56</nivel>
      <tipo>Fantasma</tipo>
      <tipo>Veneno</tipo>
      </pokemon>
      <pokemon>
      <nombre>Golbat</nombre>
      <nivel>56</nivel>
      <tipo>Veneno</tipo>
      <tipo>Volador</tipo>
      </pokemon>
      <pokemon>
      <nombre>Haunter</nombre>
      <nivel>55</nivel>
      <tipo>Fantasma</tipo>
      <tipo>Veneno</tipo>
      </pokemon>
      <pokemon>
      <nombre>Arbok</nombre>
      <nivel>58</nivel>
      <tipo>Veneno</tipo>
      </pokemon>
      <pokemon>
      <nombre>Gengar</nombre>
      <nivel>60</nivel>
      <tipo>Fantasma</tipo>
      <tipo>Veneno</tipo>
      </pokemon>
      </equipo>
    </entrenador>
    <entrenador>
      <nombre>Lance</nombre>
      <especialidad>Dragon</especialidad>
      <equipo>
      <titulo>EQUIPO</titulo>
      <pokemon>
      <nombre>Dragonite</nombre>
      <nivel>62</nivel>
      <tipo>Dragon</tipo>
      <tipo>Volador</tipo>
      </pokemon>
      <pokemon>
      <nombre>Dragonair</nombre>
      <nivel>56</nivel>
      <tipo>Dragon</tipo>
      </pokemon>
      <pokemon>
      <nombre>Dragonair</nombre>
      <nivel>56</nivel>
      <tipo>Dragon</tipo>
      </pokemon>
      <pokemon>
      <nombre>Gyarados</nombre>
      <nivel>58</nivel>
      <tipo>Agua</tipo>
      <tipo>Volador</tipo>
      </pokemon>
      <pokemon>
      <nombre>Aerodactyl</nombre>
      <nivel>60</nivel>
      <tipo>Roca</tipo>
      <tipo>Volador</tipo>
      </pokemon>
      </equipo>
    </entrenador>
  </altomando>
  <campeon>
  <titulo>CAMPEON</titulo>
      <entrenador>
      <nombre>Azul</nombre>
      <especialidad>Varios</especialidad>
      <equipo>
      <titulo>EQUIPO</titulo>
      <pokemon>
      <nombre>Pidgeot</nombre>
      <nivel>62</nivel>
      <tipo>Normal</tipo>
      <tipo>Volador</tipo>
      </pokemon>
      <pokemon>
      <nombre>Gyarados</nombre>
      <nivel>63</nivel>
      <tipo>Agua</tipo>
      <tipo>Volador</tipo>
      </pokemon>
      <pokemon>
      <nombre>Alakazam</nombre>
      <nivel>59</nivel>
      <tipo>Psiquico</tipo>
      </pokemon>
      <pokemon>
      <nombre>Exeggutor</nombre>
      <nivel>61</nivel>
      <tipo>Planta</tipo>
      <tipo>Psiquico</tipo>
      </pokemon>
      <pokemon>
      <nombre>Rhydon</nombre>
      <nivel>61</nivel>
      <tipo>Tierra</tipo>
      <tipo>Roca</tipo>
      </pokemon>
      <pokemon>
      <nombre>Charizard</nombre>
      <nivel>65</nivel>
      <tipo>Fuego</tipo>
      <tipo>Volador</tipo>
      </pokemon>
      </equipo>
    </entrenador>
  </campeon>
</ligapokemon>
